name: workday_scraper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - appdirs=1.4.4
  - beautifulsoup4=4.13.4
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates
  - certifi
  - charset-normalizer=3.3.2
  - click=8.1.8
  - colorama=0.4.6
  - git-changelog=2.4.0
  - idna=3.7
  - intel-openmp
  - jinja2=3.1.6
  - libffi
  - markupsafe=3.0.2
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - numexpr=2.10.1
  - numpy=2.0.1
  - openssl
  - pandas=2.2.3
  - pip
  - pysocks=1.7.1
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - requests=2.32.3
  - semver=3.0.2
  - setuptools
  - six=1.17.0
  - soupsieve=2.5
  - sqlite
  - tbb
  - tk
  - tomli=2.0.1
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - tzdata
  - urllib3=2.3.0
  - wheel
  - xz
  - yaml
  - zlib
  - pip:
      - html2text==2025.4.15
